### ISSUE TITLE
Non-ascii input triggers out of bounds exception

### ISSUE THREAD

**Issue by snomos** [roguePanda/MacVoikko#4]
To repeat:
* build and install MacVoikko
* open a document in any editor with MacVoikko
* input e.g. "giellá", and notice how there will be an exception in the console, and that there will be no red underline even though the input is not accepted by the speller

The problem is found in the function enumerateTokens: withBlock: in CocoaVoikko.m, but I am not able to see how to solve it. Inspiration can probably be found in the VoikkoSpellService project (https://github.com/walokra/osxspell), in the function "spellServer: findMisspelledWordInString: language: wordCount: countOnly:" in VoikkoSpellService.m.

**Comment by roguePanda** [comment]
I think the problem is that `voikkoNextTokenCstr` is in terms of bytes while `[NSString substringWithRange]` is in terms of characters. For ASCII, those are the same, so I wouldn't have noticed earlier.

**Comment by roguePanda** [comment]
I just pushed some changes. Would you mind trying them out?

**Comment by snomos** [comment]
3. jan. 2015 kl. 17:00 skrev Ben Navetta <notifications@github.com>:
> I just pushed some changes. Would you mind trying them out?

Thanks, I did, and the changes seem to fix the bug. The problems I saw have disappeared, and misspellings are correctly flagged both with and without non-ascii chars :-)

**Comment by roguePanda** [comment]
Great!
